INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('n1', 100);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('n2', 200);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('n3', 300);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('n4', 400);
